from datetime import datetime


class IncidentReportGenerator:
    """
    Generates a SOC incident investigation report
    from a stored Wazuh alert.
    """

    @staticmethod
    def generate(alert):

        lines = []

        lines.append("=" * 70)
        lines.append("SOC INVESTIGATION COPILOT")
        lines.append("INCIDENT INVESTIGATION REPORT")
        lines.append("=" * 70)

        lines.append("")

        # Alert information
        lines.append("ALERT INFORMATION")
        lines.append("-" * 70)

        lines.append(
            f"Alert ID          : {alert.get('alert_id', '')}"
        )

        lines.append(
            f"Agent             : {alert.get('agent_name', '')}"
        )

        lines.append(
            f"Agent IP          : {alert.get('agent_ip', '')}"
        )

        lines.append(
            f"Timestamp         : {alert.get('timestamp', '')}"
        )

        lines.append(
            f"Investigation     : {alert.get('investigation_status', '')}"
        )

        lines.append("")

        # Rule information
        lines.append("WAZUH RULE")
        lines.append("-" * 70)

        lines.append(
            f"Rule ID           : {alert.get('rule_id', '')}"
        )

        lines.append(
            f"Wazuh Level       : {alert.get('wazuh_level', '')}"
        )

        lines.append(
            f"SOC Severity      : {alert.get('soc_severity', '')}"
        )

        lines.append(
            f"Description       : {alert.get('rule_description', '')}"
        )

        lines.append("")

        # Risk assessment
        lines.append("RISK ASSESSMENT")
        lines.append("-" * 70)

        lines.append(
            f"Risk Score        : {alert.get('risk_score', 0)}/100"
        )

        lines.append(
            f"Risk Level        : {alert.get('risk_level', '')}"
        )

        lines.append("")

        # MITRE
        lines.append("MITRE ATT&CK")
        lines.append("-" * 70)

        lines.append(
            f"Technique ID      : {alert.get('mitre_id', '')}"
        )

        lines.append(
            f"Tactic            : {alert.get('mitre_tactic', '')}"
        )

        lines.append(
            f"Technique         : {alert.get('mitre_technique', '')}"
        )

        lines.append("")

        # User/process
        lines.append("PROCESS AND USER INFORMATION")
        lines.append("-" * 70)

        lines.append(
            f"Process           : {alert.get('process_image', '')}"
        )

        lines.append(
            f"Parent Process    : {alert.get('parent_process', '')}"
        )

        lines.append(
            f"User              : {alert.get('user_name', '')}"
        )

        lines.append("")

        # Findings
        lines.append("INVESTIGATION FINDINGS")
        lines.append("-" * 70)

        findings = alert.get("findings", [])

        if findings:

            for number, finding in enumerate(
                findings,
                start=1
            ):

                lines.append(
                    f"{number}. {finding}"
                )

        else:

            lines.append(
                "No investigation findings available."
            )

        lines.append("")

        # Recommendations
        lines.append("RECOMMENDATIONS")
        lines.append("-" * 70)

        recommendations = alert.get(
            "recommendations",
            []
        )

        if recommendations:

            for number, recommendation in enumerate(
                recommendations,
                start=1
            ):

                lines.append(
                    f"{number}. {recommendation}"
                )

        else:

            lines.append(
                "No recommendations available."
            )

        lines.append("")

        lines.append("=" * 70)

        lines.append(
            "Generated by SOC Investigation Copilot"
        )

        lines.append(
            f"Generated at      : {datetime.now().isoformat()}"
        )

        lines.append("=" * 70)

        return "\n".join(lines)